#1. 
CREATE TABLE BOOK_INFO(
	BOOK_NUM INT PRIMARY KEY
	, TITLE VARCHAR(30) NOT NULL
	, AUTHOR VARCHAR(20) NOT NULL
	, PRICE INT
	, PUBLISHER VARCHAR(20) DEFAULT '미지정'
	, BOOK_DATE DATE
);

#2.
INSERT INTO BOOK_INFO(
	BOOK_NUM, TITLE, AUTHOR, PRICE, PUBLISHER, BOOK_DATE
) VALUES(101, '자바 기초', '홍길동', 30000, 'A출판', '2025-02-15');
INSERT INTO BOOK_INFO(
	BOOK_NUM, TITLE, AUTHOR, PRICE, PUBLISHER, BOOK_DATE
) VALUES(102, '리액트 기초', '이순신', 20000, 'B출판', '2025-01-22');

#3.
UPDATE BOOK_INFO
SET 
 TITLE = '자바_고급'
 , PRICE = 25000
 , PUBLISHER = 'IT출판'
WHERE BOOK_NUM = 101;

#4.
SELECT
	EMPNO
	, ENAME
	, SAL
	, COMM AS 인센티브
FROM emp
WHERE SAL BETWEEN 500 AND 3000
AND COMM IS NOT NULL;

#5.
SELECT
	EMPNO
	, ENAME
	, JOB
	, HIREDATE
FROM emp
WHERE ENAME LIKE '%병%' 
OR ENAME LIKE '%김%'
ORDER BY JOB ASC, EMPNO DESC;

#6.
SELECT
	EMPNO
	, ENAME
	, DEPTNO
	, CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부'
		END AS 부서명
FROM emp;

#7.

SELECT
	EMPNO
	, ENAME
	, SAL
	, JOB
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE JOB != '사장')
AND JOB != '사장';

#8.
SELECT
	EMPNO
	, ENAME
	, SAL
	, COMM
	, (SAL * 12 + NVL(COMM, 0)) AS TOTAL_SALARY
FROM emp
ORDER BY TOTAL_SALARY DESC;

#9.
SELECT
	EMPNO
	, ENAME
	, MGR
	, (SELECT ENAME FROM emp E WHERE emp.MGR = E.EMPNO) AS 직속상사명
FROM emp;


#10.
# 1개

COMMIT;

