# 1.
CREATE TABLE MY_MEMBER(
	MEM_NUM INT PRIMARY KEY
	, MEM_ID VARCHAR(30) NOT NULL
	, MEM_PW VARCHAR(30) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, AGE INT
	, EMAIL VARCHAR(50) UNIQUE
);

# 2.
INSERT INTO MY_MEMBER(MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, AGE, EMAIL) VALUES(101, 'kim', '1234', '김자바', 30, 'kim@gmail.com');
INSERT INTO MY_MEMBER(MEM_NUM, MEM_ID, MEM_PW, MEM_NAME, AGE, EMAIL) VALUES(102, 'hong', '5678', '홍자바', 25, 'hong@gmail.com');

# 3.
UPDATE
SET MY_MEMBER
 MEM_NAME = '유관순'
 , AGE = AGE + 5
WHERE MEM_NUM = 101; 

# 4.
SELECT
	EMPNO
	, ENAME
	, SAL
	, COMM
FROM EMP
WHERE SAL BEWEEN 500 AND 3000
AND COMM IS NOT NULL;

# 5.
SELECT
	EMPNO
	, ENAME
	, HIREDATE
FROM EMP
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

# 6.
SELECT
	EMPNO
	, ENAME
	, DEPTNO
	, CASE DEPTNO
		WHEN 10 THEN '인사부'
		WHEN 20 THEN '영업부'
		WHEN 30 THEN '개발부'
		ELSE '생산부'
		END AS 부서명
FROM EMP


# 7.
SELECT
	EMPNO
	, ENAME
	, HIREDATE
	, NVL(COMM, 0)
FROM EMP
WHERE HIREDATE LIKE '%-01-%'
ORDER BY HIREDATE;

# 8.
SELECT
	EMPNO
	, ENAME
	, SAL
	, JOB
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE JOB != '사장')
AND JOB != '사장';

# 9.
SELECT
	EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, DEPTNO
	, (SELECT DNAME FROM DEPT WHERE DEPTNO = EMP.DEPTNO AND DNAME = '인사부') AS 부서명
FROM EMP;

# 10.
SELECT
	EMPNO
	, ENAME
	, HIREDATE
	, SAL
	, D.DEPTNO
	, DNAME
FROM EMP E
INNER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE DNAME != '인사부'
AND SAL >= 500
ORDER BY EMPNO DESC, ENAME ASC;

